{{- if .Values.networkPolicy.enabled -}}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "influxdb.fullname" . }}
  labels:
    {{- include "influxdb.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "cookie-cutter.selectorLabels" . | nindent 6 }}
  {{- with .Values.networkPolicy.ingress }}
  ingress:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.networkPolicy.egress }}
  egress:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  policyTypes:
  {{- with .Values.networkPolicy.ingress }}
    - Ingress
  {{- end }}
  {{- with .Values.networkPolicy.egress }}
    - Egress
  {{- end }}
{{- end }}
